services:
  os_api:
    container_name: api_os
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres_os;Database=interfocus;Username=postgres;Password=postgres@123
    ports:
      - "8080:8080"
    networks:
      - services
    depends_on:
      - db 
    entrypoint: ["dotnet", "ApiCrud.dll"]

  db:
    image: postgres:latest
    container_name: postgres_os
    environment:
      POSTGRES_DB: interfocus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - services
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

networks:
  services:
    driver: bridge
