version: '3.8'

services:
  os_api:
    image: url_imagem_gitlab 
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_HTTP_PORTS=8080 
    networks:
      - ingress-network  
      - services  
    deploy:
      labels:
        caddy: nome_da_sua_aplicacao.labs.unimar.br 
        caddy.reverse_proxy: "{{upstreams 8080}}"  
      resources:
        limits:
          cpus: '0.25'
          memory: 512M  

networks:
  services: {}
  ingress-network:
    external: true 
